### ISSUE TITLE
Libtools required to compile, also, the readme lacks compiling instructions.

### ISSUE THREAD

**Issue by geeklhem** [stoufferlab/msp-boxes#1]
When running `autoconf` I get: 

```
configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

`aclocal` fixes this. 

But then, when running `./configure` yields

```
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

By trial and errors I managed to get it work using `autoreconf -f -i`

then `./configure; make;`. But it could be easier, or at least documented.

**Comment by stouffer** [comment]
You shouldn't need libtool to be installed, but yes, a note in the readme that one should run `autoreconf --install` first can't hurt.
